const Homeproduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '26',
        image: 'image/laptop.jpg',
        cat: 'laptop',
        type: 'new',
        qty: 1,
    },
    {
        id: 2,
        Name: 'product2',
        price: '96',
        image: 'image/bluethooth.jpg',
        cat: 'bluethooth',
        type: 'new',
        qty: 1,
    },
    {
        id: 3,
        Name: 'product3',
        price: '106',
        image: 'image/iPhone 15.jpg',
        cat: 'iPhone 15',
        type: 'new',
        qty: 1,
    },
    {
        id: 4,
        Name: 'product4',
        price: '636',
        image: 'image/App watch 2.jpg',
        cat: 'Apple Watch 2',
        type: 'new',
        qty: 1,
    },
    {
        id: 5,
        Name: 'product5',
        price: '116',
        image: 'image/cctv.jpg',
        cat: 'cctv',
        type: 'featured',
        qty: 1,
    },
    {
        id: 6,
        Name: 'product6',
        price: '126',
        image: 'image/iPhone 12.jpg',
        cat: 'iPhone 13',
        type: 'featured',
        qty: 1,
    },
    {
        id: 7,
        Name: 'product7',
        price: '956',
        image: 'image/iPhone 11pro max.jpg',
        cat: 'iPhone 11pro max',
        type: 'featured',
        qty: 1,
    },
    {
        id: 8,
        Name: 'product8',
        price: '389',
        image: 'image/iPhone 11pro.jpg',
        cat: 'iPhone 11pro',
        type: 'featured',
        qty: 1,
    },
    {
        id: 9,
        Name: 'product9',
        price: '146',
        image: 'image/Tv.jpg',
        cat: 'tv',
        type: 'top',
        qty: 1,
    },
    {
        id: 10,
        Name: 'product10',
        price: '156',
        image: 'image/bluethooth2.jpg',
        cat: 'bluethooth 2',
        type: 'top',
        qty: 1,
    },
    {
        id: 11,
        Name: 'product11',
        price: '416',
        image: 'image/iPhone 12.jpg',
        cat: 'iPhone 12',
        type: 'top',
        qty: 1,
    },
    {
        id: 12,
        Name: 'product12',
        price: '806',
        image: 'image/App Watch 2.jpg',
        cat: 'Apple Watch 3',
        type: 'top',
        qty: 1,
    },
]
export default Homeproduct